USE [master]
GO

/****** Object:  Database [Ocean]    Script Date: 27/1/2021 下午 3:20:33 ******/
-- CREATE DATABASE [Ocean]
--  CONTAINMENT = NONE
-- --  ON  PRIMARY 
-- -- ( NAME = N'Ocean', FILENAME = N'/sqlfiles/data/Ocean.mdf' , SIZE = 16448KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
-- --  LOG ON 
-- -- ( NAME = N'Ocean_log', FILENAME = N'/sqlfiles/data/Ocean_1.ldf' , SIZE = 61824KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
-- --  WITH CATALOG_COLLATION = DATABASE_DEFAULT
-- GO

EXEC sp_attach_db @dbname= 'Ocean',
        @filename1 = '/sqlfiles/data/Ocean.mdf',
        @filename2 = '/sqlfiles/data/Ocean_1.ldf'

GO


IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ocean].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ocean] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ocean] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ocean] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ocean] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ocean] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ocean] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Ocean] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ocean] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ocean] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ocean] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ocean] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ocean] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ocean] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ocean] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ocean] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ocean] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ocean] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ocean] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ocean] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ocean] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ocean] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ocean] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ocean] SET RECOVERY FULL 
GO

ALTER DATABASE [Ocean] SET  MULTI_USER 
GO

ALTER DATABASE [Ocean] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ocean] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Ocean] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Ocean] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Ocean] SET DELAYED_DURABILITY = DISABLED 
GO

-- ALTER DATABASE [Ocean] SET ACCELERATED_DATABASE_RECOVERY = OFF  
-- GO

ALTER DATABASE [Ocean] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Ocean] SET  READ_WRITE 
GO

